//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Order_Detail = new HashSet<Order_Detail>();
        }
    
        public long ID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ShipName { get; set; }
        public string ShipMobile { get; set; }
        public string ShipAdress { get; set; }
        public string ShipEmail { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<long> User_ID { get; set; }
        public Nullable<decimal> TotalMoney { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<System.DateTime> CancerDate { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
    
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
        public virtual User User { get; set; }
    }
}
